'''
Autor: Eduardo
Fecha: 20 sep 2022
'''

print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()
print()
print()
print("   *")
print("  * *")
print(" *   *")
print("**   **")
print("  * *")
print("  * *")
print("  ***")
print()
print()
print()
print("       *")
print("      * *")
print("     *   *")
print("    *     *")
print("   *       *")
print("  *         *")
print(" *           *")
print("*****     *****")
print("    *     *")
print("    *     *")
print("    *     *")
print("    *******")